const chapters = [
    {
        title: 'Week One',
        paragraphs: [
            'It was January 1st, 2035. The year of the Tiger. China was on the verge of civil war. Or, corporate takeover, depending on who you asked, and where you asked the question. Biyu was floating on the surface of a pool of deepest jade. Or, she was passed out with her pants down on someone else’s bare, dirty mattress. Depending on who you asked. As she floated back to her body, she realised she could hear someone trying to pry open the door to the hallway, in the next room over. She opened her eyes, and was temporarily blinded by a wall of lights and shapes. As her eyes adjusted, she realised that what she was seeing was the invisible lines of connection between all things. They looked like strings, vibrating, and colour coded, in every shade imaginable. They tugged her up, off the mattress and toward the open window. A vague memory told her it was a 32 story drop to the footpath. Biyu pulled her pants back up at the same time as the hallway door crashed open. Biyu paid no attention to the sounds of her soon to be kidnapper as he stomped through the small apartment to her door: She was too busy trying to wake up her groggy mind, still blissed out from the heroin vape she had stolen from him. She was trying to decipher what the myriad, alien lines of light were describing. They twisted and turned in the air in front of the window, like a million ribbon dancers performing for her. She felt that they wanted her, too, to twist, just so. To fall in exactly that spot. So she leapt into the web of light. Twisting, spinning, just like they told her. The man burst into the room just in time to see Biyu launch herself, cackling and triumphant, off the windowsill and out into the void.'
        ]
    },
    {
        title: 'Week Two',
        paragraphs: [
            'It was January 1st, 2035. The year of the tiger. Bohai didn’t so much as wake up on the hardwood floor of the clubhouse, it was more a case of him stopping being unconscious. Now that he was no longer unconscious, he could go to sleep, if he so wished. But he didn’t. Bohai was fucked. This New Year’s eve he had started drinking early. His only real girlfriend since highschool had disappeared on him. Overnight, she had packed up her apartment and turned to a ghost. This had gotten Bohai in just the right mood for a kind of binging entirely inappropriate for a man his age. The last few days were a blur of drinking, drugs, and spending almost everything he had.',
            '“I should have just stuck with a sex doll.” Bohai croaked to himself. He was covered in a film of old sweat, and it made his clothes feel uncomfortable, like they didn’t fit. He lay there, feeling it all. In a way, this hangover hurt more than the heartbreak that had caused it. “I guess that’s the point. Remind you how much worse things can be.” As Bohai’s body slowly came back to life he realised how good the floor polish smelled. A dark, heavy smell. It smelled like espresso coffee tastes. He clung to it. “Fuck, I miss her.” He thought. Bohai clung to that, too. ',
            'An hour later, after nearly passing out again in the narrow shower cubicle, Bohai sat down at the Club’s cafe. He had scavenged a fairly clean t-shirt from the changing room and a couple of relatively unused socks, but was otherwise wearing the same clothes. Dirty sneakers, black denim pants, and the Club uniform jacket, bearing the insignia of organised crime in Chongqing: Peppa Pig. And on Peppa’s dress, the Chinese character for strength. Bohai sat on his own, and ordered a bowl of breakfast rice noodles. He was slumped on a chair thinking about how his left foot felt strangely swollen when he was approached by Wenao, who shuffled to the table with a large coffee in each hand, and slumped into a chair. He moved simultaneously deliberate, and clumsy. A hangover affected him differently because of the augmentations he’d received while serving in the People’s Army. ',
            '“Morning.” Said Wenao, after an awkward pause. ',
            '“Yo.” Grunted Bohai. “Feeling fucked as I am?”',
            '“Not a chance.” Wenao sat back, opened up his posture and smiled. He reached into his jacket pocket for a bottle of dark brown liquor. He poured a cap into his coffee, and put the cap and bottle on the table. Bohai ignored him, just went for his noodles. They both sat in silence for a bit, Wenao sipping his coffee and staring levelly at the wall, Bohai eating, face to bowl. As Bohai started to slow he looked to his friend and asked. “So, where is everyone?” ',
            '“Well to start with, it’s mid afternoon.”',
            '“Oh. Still, kinda weird to see the place so empty.”',
            '“Yeah. Probably at Mrs Yang’s. A woman can be great comfort to a man with a hangover.” ',
            'Bohai grimaced. “Sure can.” He pushed his half finished bowl aside and poured a glug of liquor in his coffee. They both sat, looking out with bloodshot eyes at the world at large. Wenao felt that his inner self had retreated so far within that he was at the bottom of a pond. He lay there on his back, having to reach all the way up through the murky waters of his body just to sip his irish coffee. Wenao looked through the door to the kitchen. The new kitchen hand was methodically working his way through a sink full of pots. Outside, the sun was shining. Two sparrows followed a man in an open throated suit as he ambled toward the clubhouse, eating a pastry. They fed on the crumbs for a short while, until they were startled by the sound of gunfire, and flew away. ',
            'The man in the suit threw the cafe doors open and stomped inside. “Show me to the Spider!” He roared the words, jolting Bohai and Wenao from their reverie. “Party business!”',
            '“How the fuck do you know that name!” Bohai jumped to his feet, knocking his chair to the ground in the process. ',
            '“I’m only going to say it once, Party business.” The man said squaring his feet. “She fucked up and she owes me. Now get her, lackey.”',
            '“I’m going to break your neck!” Bohai shouted, stomping toward the man. When he was no more than three long strides away, the man in the suit pulled a gun from his armpit holster, stopping Bohai dead in his tracks. It was black, deadly looking thing, made of heavy metal. ',
            '“Sit the fuck down, lackey. There you go, son.” He hooked a wooden chair with one foot and sent it skidding across the floor. Bohai grabbed it and sat down. He looked unreasonably furious. Wenao had ducked out of view of the intruder and was scuttling under the tables toward the exit, back into the main room of the clubhouse. ',
            '“Hey! I don’t want to shoot you, I just need to talk to the Spider!”',
            'Wenao had made it to his last piece of cover, a table which was at least two running steps from the doorway. An impossible distance with a gun trained on you.',
            '“You better call for backup, son.” Bohai spat the last word at the man, who was at least ten years younger than him.',
            '“I don’t want to have to shoot you!” The man repeated, ignoring Bohai. ',
            '“Ok, ok!” Wenao shouted back from under the table. “I’m coming out! Don’t shoot!”',
            '“Sure, I won’t shoot.” ',
            'There was a brief pause, and Wenao popped up, two tables closer than the one he had just been speaking from. He lobbed the half finished remains of Bohai’s breakfast at the man’s head, and screamed, ducking back behind shelter. The man took one shot at Wenao, which embedded itself in the heavy wooden table. He ducked to avoid the bowl of soup, then tried to take a shot at Bohai. Too late. Bohai had jumped from his chair, quick and malevolent as a hungry panther, and was on him in a second. He grabbed the man’s wrist, causing the shot to go wide, and yanked him in. Both men were pulled together, one wide eyed and scrabbling, the other angry, bloodshot, and still high from last night’s amphetamines. The intruder punched Bohai in the face with his free hand. But they were too close together, so there was no real power behind it. Bohai pulled in his opponent in a hug, and sunk his teeth into the man’s neck. He bit with fury, with killing intent. The man in the suit screamed a horrible, guttural scream. It was cut short by Bohai’s forehead connecting with the man’s face. Bohai switched postures, grabbing his opponent’s neck and headbutting him three more times, in quick succession. The man, whoever he was, slumped to the floor, bleeding openly from the face and neck. Bohai stood over him, heaving deep, shaky breaths. For a minute, it was silent. Bohai was looking down at the intruder. The dishwasher was peering out around the kitchen door at Bohai. Wenao was watching the kitchenhand. And, over the security cameras, the Spider watched them both. Outside, the sun was shining, and the sparrows were chirping. '
        ]
    }
]

export default chapters